
const data = [
    {
        id: 1,
        img: '#',
        alt: 'skills',
        desc: 'HTML',
        link: '#',
        target: 'target=”_blank”',
        github: '#',
    },
    {
        id: 2,
        img: '/images/HyperTech.png',
        alt: 'skills',
        desc: 'CSS',
        link: '',
        target: 'target=”_blank”',
    },
    {
        id: 3,
        img: '/images/GPT.png',
        alt: 'skills',
        desc: 'JavaScript',
        link: 'https://curious-mermaid-adc704.netlify.app/',
        target: 'target=”_blank”',
    },
    {
        id: 4,
        img: '/images/flags.png',
        alt: 'skills',
        desc: 'React',
        link: '',
        target: 'target=”_blank”',
    },
    {
        id: 5,
        img: '#',
        alt: 'skills',
        desc: 'Bootstrap',
        link: '',
        target: 'target=”_blank”',
    },
    {
        id: 6,
        img: '#',
        alt: 'skills',
        desc: 'Tailwind',
        link: '',
        target: 'target=”_blank”',
    },
    {
        id: 7,
        img: '#',
        alt: 'skills',
        desc: 'MaterialUI',
        link: '',
        target: 'target=”_blank”',
    },
    {
        id: 8,
        img: '#',
        alt: 'skills',
        desc: 'C',
        link: '',
        target: 'target=”_blank”',
    },
    {
        id: 9,
        img: '#',
        alt: 'skills',
        desc: 'C++',
        link: '',
        target: 'target=”_blank”',
    },
    {
        id: 10,
        img: '#',
        alt: 'skills',
        desc: 'Java',
        link: '',
        target: 'target=”_blank”',
    },
    {
        id: 11,
        img: '#',
        alt: 'skills',
        desc: 'Linux',
        link: '',
        target: 'target=”_blank”',
    },
    {
        id: 12,
        img: '#',
        alt: 'skills',
        desc: 'PHP',
        link: '',
        target: 'target=”_blank”',
    }
]

export default data;