
const data = [
    {
        id: 14,
        img: '/images/besteats.png',
        alt: 'skills',
        desc: 'React',
        link: 'https://besteat.netlify.app/',
        github: 'https://github.com/SamaelMarjan/res',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 15,
        img: '/images/netflix.png',
        alt: 'skills',
        desc: 'React',
        link: 'https://nnetflixx.netlify.app/',
        github: 'https://github.com/SamaelMarjan/netflixClone',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 16,
        img: '/images/digi.png',
        alt: 'skills',
        desc: 'HTML, Tailwind CSS, React',
        link: 'https://landing001.netlify.app/',
        github: 'https://github.com/SamaelMarjan/landing01',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 6,
        img: '/images/engine.png',
        alt: 'skills',
        desc: 'Tailwind',
        link: 'https://enginereact.netlify.app/',
        github: 'https://github.com/SamaelMarjan/engine_react',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 7,
        img: '/images/blog.png',
        alt: 'skills',
        desc: 'TailwindCss',
        link: 'https://bloggss.netlify.app/',
        github: 'https://github.com/SamaelMarjan/blog',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 13,
        img: '/images/todo.png',
        alt: 'skills',
        desc: 'React',
        link: 'https://sams-todo.netlify.app/',
        github: 'https://github.com/SamaelMarjan/toDo',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 1,
        img: '/images/swapno.png',
        alt: 'skills',
        desc: 'HTML',
        link: 'https://swapnochura.netlify.app/',
        github: 'https://github.com/SamaelMarjan/swapnochura',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 2,
        img: '/images/HyperTech.png',
        alt: 'skills',
        desc: 'CSS',
        link: '',
        github: '',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 3,
        img: '/images/GPT.png',
        alt: 'skills',
        desc: 'JavaScript',
        link: 'https://curious-mermaid-adc704.netlify.app/',
        github: 'https://github.com/SamaelMarjan/gpt3',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 4,
        img: '/images/flags.png',
        alt: 'skills',
        desc: 'React',
        link: 'https://all-country-flags.netlify.app/',
        github: 'https://github.com/SamaelMarjan/country_flags',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 5,
        img: '/images/list.png',
        alt: 'skills',
        desc: 'Bootstrap',
        link: 'https://listcon.netlify.app/',
        github: 'https://github.com/SamaelMarjan/tour_list',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    
    
    {
        id: 8,
        img: '#',
        alt: 'skills',
        desc: 'C',
        link: '',
        github: '',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 9,
        img: '#',
        alt: 'skills',
        desc: 'C++',
        link: '',
        github: '',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 10,
        img: '#',
        alt: 'skills',
        desc: 'Java',
        link: '',
        github: '',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 11,
        img: '#',
        alt: 'skills',
        desc: 'Linux',
        link: '',
        github: '',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    },
    {
        id: 12,
        img: '#',
        alt: 'skills',
        desc: 'PHP',
        link: '',
        github: '',
        target: 'target=”_blank”',
        p: 'under construction but you can see the live work',
    }
]

export default data;